
export const types = {
    LOGIN_SUCCESS: '[auth] LOGIN_SUCCESS',
    LOGIN_ERROR: '[auth] LOGIN_ERROR',
    
    USER_AUTHENTICATED: '[auth] USER_AUTHENTICATED',

    REGISTER_SUCCESS: '[auth] REGISTER_SUCCESS',
    REGISTER_ERROR: '[auth] REGISTER_ERROR',

    LOGOUT: '[auth] LOGOUT',

    UPLOAD_FILE: '[app] UPLOAD_FILE',
    UPLOAD_FILE_SUCCESS: '[app] UPLOAD_FILE_SUCCESS',
    UPLOAD_FILE_ERROR: '[app] UPLOAD_FILE_SUCCESS',
    
    CREATE_LINK_SUCCESS: '[app] CREATE_LINK_SUCCESS',
    CREATE_LINK_ERROR: '[app] CREATE_LINK_ERROR',

    CLEAN_STATE: '[app] CLEAN_STATE',

    SHOW_ALERT: '[ui] SHOW_ALERT',
    HIDE_ALERT: '[ui] HIDE_ALERT',
}